---
- name: Etckeeper Playbook
  apt: "pkg=etckeeper state=latest"
 
- name: Set for git
  lineinfile: dest=/etc/etckeeper/etckeeper.conf regexp=^VCS= line=VCS="git"
  lineinfile: dest=/etc/etckeeper/etckeeper.conf regexp=^VCS="bzr" state=absent
  
- stat: path=/etc/.git
  register: p
  
- command: etckeeper init;etckeeper commit -m "initial"
  when: p.stat.isdir is not defined
