#!/usr/bin/env ruby
site "https://galaxy.ansible.com/api/v1"

role "devbox.chrome"
role "franklinkim.fail2ban"
role "ansible-scala", github: "AnsibleShipyard/ansible-scala"

role "role.dumpvars", github: "rjordan/role.dumpvars"
role "role.ansible", github: "rjordan/role.ansible"
role "role.nfs-client", github: "rjordan/role.nfs-client"
role "role.ssh", github: "rjordan/role.ssh"
role "role.ubuntu-updates", github: "rjordan/role.ubuntu-updates"
role "role.bind", github:"resmo/ansible-role-bind"
role "role.scala", github: "rjordan/role.scala"
role "role.basics", github: "rjordan/role.basics"
role "role.docker", github: "rjordan/role.docker"
role "role.ufw", github: "rjordan/role.ufw"
role "role.java-runtime", github: "rjordan/role.java-runtime"


