---
- name: Default programs 
  hosts: all
  become: true 
#  tasks:
#    - name: Dump vars
#      action: template src=templates/dumpall.j2 dest=/tmp/ansible.all
#      changed_when: false
  roles:
#    - role.ubuntu-updates
    - role.ssh
    - role.basics
    - role.ufw
- name: Workstations    
  hosts: 
    - workstations
  become: true 
  roles:
    - role.java-runtime    
    - role.nfs-client
    - devbox.chrome
- name: Fail2Ban
  hosts: 
    - ubuntu-dvr.codecrusade.org
  become: true 
  roles:
    - franklinkim.fail2ban    
- name: Development
  hosts: 
    - dev-boxes
  become: true 
  roles:
    - role.ansible
    - role.docker
    - franklinkim.fail2ban
    - role.scala
- name: Docker
  hosts: 
    - docker2.codecrusade.org
  become: true 
  roles:
    - role.docker
    - role.nfs-client
#  tasks:
#    - mount: name=/srv/docker-data src=nfs.codecrusade.org:/srv/docker-data fstype=nfs4 opts=noatime state=mounted
- name: Docker
  hosts: 
    - web1.codecrusade.org
    - docker2.codecrusade.org
  become: true 
  vars:
    consul_datacenter: home 
  roles:
    - role.consul

