---
- name: Default programs 
  hosts: all
  sudo: true
  tasks:
    - name: Dump vars
      action: template src=templates/dumpall.j2 dest=/tmp/ansible.all
      changed_when: false
  roles:
    - role.ubuntu-updates
    - role.ssh
    - role.basics
    - role.ufw
- name: Workstations    
  hosts: 
    - workstations
  sudo: true
  roles:
    - role.java-runtime    
    - role.nfs-client
    - devbox.chrome
- name: Development
  hosts: 
    - dev-boxes
  sudo: true
  roles:
    - role.ansible
    - role.docker
    - franklinkim.fail2ban
    - role.scala
- name: Docker
  hosts: 
    - docker
  sudo: true  
  roles:
    - role.docker
    - role.nfs-client
#  tasks:
#    - mount: name=/srv/docker-data src=nfs.codecrusade.org:/srv/docker-data fstype=nfs4 opts=noatime state=mounted

