---
- name: Default programs 
  hosts: all
  sudo: true
  roles:
    - role.ubuntu-updates
    - role.ssh
    - role.curl
    - role.ntp
- name: Development
  hosts: 
    - dev-boxs
  sudo: true
  roles:
    - role.ufw #TODO Move up with more config
    - role.ansible
    - role.docker
    - role.git
    - role.java-runtime    
- name: Docker
  hosts: 
    - docker
  sudo: true  
  roles:
    - role.docker

