---
- name: Default programs 
  hosts: all
  sudo: true
  roles:
    - role.git
    - role.etckeeper
    - role.ssh
    - role.fail2ban
    - role.curl
    - role.ntp

- name: Development
  hosts: 
    - megatraveler
  sudo: true
  roles:
    - role.java-runtime
    - role.ufw #TODO Move up with more config

- name: Docker
  hosts: 
    - megatraveler
    - docker
  sudo: true  
  roles:
    - role.docker
  
- name: Ansible server
  hosts: ansible
  sudo: true
  roles:
    - role.ansible
