---
- name: Default programs 
  hosts: all
  sudo: true
  roles:
    - rjordan.ubuntu-updates
    - rjordan.ssh
    - rjordan.curl
    - rjordan.ntp
- name: Development
  hosts: 
    - dev-boxs
  sudo: true
  roles:
    - rjordan.ufw #TODO Move up with more config
    - rjordan.ansible
    - rjordan.docker
    - rjordan.git
    - rjordan.java-runtime    
- name: Docker
  hosts: 
    - docker
  sudo: true  
  roles:
    - rjordan.docker

