---
- name: Developer Playbook 
  hosts: local
  sudo: true
  roles:
    - role.ubuntu-updates
    - role.ansible
    - role.docker
    - role.curl
    - role.ntp
    - role.git
    - role.ssh
    - role.java-runtime
#    - role.ruby-system
#    - role.chrome

