---
- name: Development
  hosts: dev-boxes
  become: true 
  tasks:
    - name: Basic Packages
      apt: "pkg={{item}} state=latest"
      with_items:
      - git
  roles:
    - rjordan.ansible
    - rjordan.docker
    - rjordan.java-runtime  
    - rjordan.scala
 

