---
- name: Logstash Forward
  hosts: all
  sudo: true
  tasks: 
    - copy: src=files/01-logstash.conf dest=/etc/rsyslog.d/01-logstash.conf 
      register: ls_config
    - service: name=rsyslog state=restarted
      when: ls_config.changed
      
- name: Containers
  hosts:
    - docker
  tasks:  
    - name: registrator
      docker:
        name: registrator
        image: gliderlabs/registrator
        pull: always
        state: reloaded
        net: host
        command: "consul://{{ansible_default_ipv4.address}}:8500 '-ip {{ansible_default_ipv4.address}}' '-resync 300'"
        volumes:
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
    
