---
 - src: rjordan.dumpvars
 - src: rjordan.ubuntu-updates
 - src: franklinkim.fail2ban
 - src: cmprescott.chrome
 - src: franklinkim.nginx
 - src: savagegus.consul
 - src: geerlingguy.nginx
 - src: joshualund.golang
 - src: rjordan.ansible
 - src: rjordan.docker
 - src: rjordan.nfs-client
 - src: rjordan.consul
 - src: rjordan.ssh
 - src: rjordan.java-runtime
 - src: rjordan.ufw
 - src: rjordan.scala
 - src: https://github.com/rjordan/role.devtools
   version: master
   name: rjordan.devtools

# devbox.chrome
# rjordan.basics
# rjordan.bind

