---
- name: Default programs
  hosts: all
  sudo: true
  vars:
    test_value: "{{ lookup('consul_kv', 'gamemaster/production/DB_USER') }}"
#    consul_datacenter: home 
#    consul_server: true
  tasks:
    - debug: msg="{{test_value}}"
  roles:
#  - role.consul
#  - role: role.bind
#    bind_config_recursion: "yes"
#    bind_config_master_zones:
#      - name: codecrusade.org
#      - name: 168.192.in-addr.arpa
#    bind_config_forward_zones:
#      - name: Domains for consul
#        forwarders:
#          - "127.0.0.1 port 8600"
#        forward: only
#        zones:
#          - consul
#    bind_config_master_forwarders:
#      - "8.8.8.8"
#      - "8.8.4.4"

