---
- name: Default programs
  hosts: docker
  # remote_user: ubuntu
  become: true
  vars:
    docker:
      test2:
    ldap_auth_uri: ldap://192.168.0.200/
    ldap_auth_base_dc: DC=codecrusade,DC=org
    ldap_auth_root_bind_dn: CN=admin,DC=codecrusade,DC=org
  #    consul_datacenter: home
  #    consul_server: true
  tasks:
    - name: debug
      debug: msg="{{docker}}"
  roles:
#    - role: rjordan.ldap-auth-client
#  - role.consul
#  - role: role.bind
#    bind_config_recursion: "yes"
#    bind_config_master_zones:
#      - name: codecrusade.org
#      - name: 168.192.in-addr.arpa
#    bind_config_forward_zones:
#      - name: Domains for consul
#        forwarders:
#          - "127.0.0.1 port 8600"
#        forward: only
#        zones:
#          - consul
#    bind_config_master_forwarders:
#      - "8.8.8.8"
#      - "8.8.4.4"
